import SwiftUI

struct CreateEventView: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var appState: AppState
    @State private var title = ""
    @State private var location = ""
    @State private var startDate: Date
    @State private var endDate: Date
    @State private var description = ""
    @State private var category: EventCategory = .academic
    @State private var saveToDeviceCalendar = true
    @State private var isSaving = false
    @State private var errorMessage: String?
    
    private let calendarService = CalendarService()
    
    init(initialDate: Date = Date()) {
        _startDate = State(initialValue: initialDate)
        _endDate = State(initialValue: initialDate.addingTimeInterval(3600))
    }

    var body: some View {
        Form {
            Section("Event Details") {
                TextField("Title", text: $title)
                TextField("Location", text: $location)
                DatePicker("Start", selection: $startDate)
                DatePicker("End", selection: $endDate)
                Picker("Category", selection: $category) {
                    ForEach(EventCategory.allCases, id: \.self) { cat in
                        Text(cat.rawValue).tag(cat)
                    }
                }
                TextField("Description", text: $description, axis: .vertical)
                    .lineLimit(3...6)
            }
            
            if appState.permissionState.calendarGranted {
                Section {
                    Toggle("Save to iOS Calendar", isOn: $saveToDeviceCalendar)
                } footer: {
                    Text("When enabled, the event will be added to your device's Calendar app.")
                }
            }
            
            if let errorMessage = errorMessage {
                Section {
                    Text(errorMessage)
                        .foregroundStyle(.red)
                        .font(.caption)
                }
            }
            
            Section {
                Button(action: save) {
                    HStack {
                        if isSaving {
                            ProgressView()
                                .scaleEffect(0.8)
                        }
                        Text(isSaving ? "Saving..." : "Save Event")
                    }
                    .frame(maxWidth: .infinity)
                }
                .disabled(title.isEmpty || isSaving)
            }
        }
        .navigationTitle("Create Event")
        .toolbar {
            ToolbarItem(placement: .cancellationAction) {
                Button("Close", action: dismiss.callAsFunction)
                    .disabled(isSaving)
            }
        }
    }

    private func save() {
        guard !title.isEmpty else { return }
        guard startDate < endDate else {
            errorMessage = "End date must be after start date"
            return
        }
        
        isSaving = true
        errorMessage = nil
        
        Task {
            do {
                let newEvent = Event(
                    id: "", // Will be generated by Firebase
                    title: title,
                    location: location,
                    startDate: startDate,
                    endDate: endDate,
                    description: description,
                    rsvp: .going,
                    category: category
                )
                
                // Save to Firebase
                let firebaseService = FirebaseService()
                try await firebaseService.save(event: newEvent, userId: appState.userProfile.id)
                
                // Optionally save to iOS Calendar
                if saveToDeviceCalendar && appState.permissionState.calendarGranted {
                    do {
                        try await calendarService.saveEventToDeviceCalendar(newEvent)
                    } catch {
                        // Log error but don't fail the whole save
                        print("Failed to save to device calendar: \(error.localizedDescription)")
                    }
                }
                
                // Refresh events after saving
                await appState.refreshCalendarEvents()
                
                await MainActor.run {
                    dismiss()
                }
            } catch {
                await MainActor.run {
                    errorMessage = "Failed to save event: \(error.localizedDescription)"
                    isSaving = false
                }
            }
        }
    }
}
